version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data: